# Creating Decision Rule Systems

In [1]:
import pandas as pd
from importlib import resources
from drdt.helper_functions import DecisionRuleCreatorFromDecisionTable
from ucimlrepo import fetch_ucirepo

# Connect-4

In [2]:
connect_4 = fetch_ucirepo(id=26) 
  
X = connect_4.data.features 
y = connect_4.data.targets

In [3]:
DecisionTable = pd.concat([X, y], axis=1)
DecisionTable

      a1 a2 a3 a4 a5 a6 b1 b2 b3 b4  ... f4 f5 f6 g1 g2 g3 g4 g5 g6 class
0      b  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
1      b  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
2      b  b  b  b  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
3      b  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
4      o  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
...   .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. ..   ...
67552  x  x  b  b  b  b  o  x  o  b  ...  b  b  b  o  o  x  b  b  b  loss
67553  x  x  b  b  b  b  o  b  b  b  ...  b  b  b  o  x  o  o  x  b  draw
67554  x  x  b  b  b  b  o  o  b  b  ...  b  b  b  o  x  x  o  b  b  loss
67555  x  o  b  b  b  b  o  b  b  b  ...  b  b  b  o  x  o  x  x  b  draw
67556  x  o  o  o  x  b  o  b  b  b  ...  b  b  b  x  b  b  b  b  b  draw

[67557 rows x 43 columns]

### Pre-processing

In [4]:
# Checking the missing values
if DecisionTable.isna().any().any():
    print("Dataset has missing values")
    DecisionTable.fillna(DecisionTable.mode().iloc[0], inplace=True) # fill with columnwise most common
else:
    print("No missing values")

No missing values

In [5]:
# Checking dublicates
if DecisionTable.iloc[:, :-1].duplicated().any():
    print("Yes there are dublicates")
    # merge dublicates and last values is the most common one
    DecisionTable = DecisionTable.groupby(list(DecisionTable.columns[:-1]))['class'].agg(lambda x: x.mode()[0]).reset_index()
else:
    print("No dublicate")

No dublicate

### Creating Decision Rule System

In [6]:
DecisionRule = DecisionRuleCreatorFromDecisionTable(DecisionTable)
DecisionRule

  0%|                                                                                                                                             | 0/67557 [00:00<?, ?it/s]/Users/durdymk/Desktop/DrDt/drdt/helper_functions.py:199: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r[mask_row] = np.nan
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 67557/67557 [9:35:25<00:00,  1.96it/s]

,a1,a2,a3,a4,a5,a6,b1,b2,b3,b4,...,f4,f5,f6,g1,g2,g3,g4,g5,g6,class
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,win
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,win
2,b,NaN,NaN,NaN,NaN,NaN,o,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,win
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,win
4,o,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,x,NaN,NaN,...,NaN,NaN,b,NaN,NaN,NaN,NaN,NaN,NaN,loss
67553,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,draw
67554,NaN,x,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,b,NaN,NaN,NaN,NaN,NaN,NaN,loss
67555,x,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,draw
67556,x,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,draw

In [7]:
DecisionRule.to_csv('/Users/durdymk/Desktop/DrDt/datasets/DecisionRuleSystems/DRS_connect_4', index=False)

# Molecular Biology (Splice-junction Gene Sequences)

In [8]:
molecular_biology_splice_junction_gene_sequences = fetch_ucirepo(id=69) 
  
X = molecular_biology_splice_junction_gene_sequences.data.features 
y = molecular_biology_splice_junction_gene_sequences.data.targets

In [9]:
DecisionTable = pd.concat([X, y], axis=1)
DecisionTable

,Base1,Base2,Base3,Base4,Base5,Base6,Base7,Base8,Base9,Base10,...,Base52,Base53,Base54,Base55,Base56,Base57,Base58,Base59,Base60,class
0,C,C,A,G,C,T,G,C,A,T,...,G,C,C,A,G,T,C,T,G,EI
1,A,G,A,C,C,C,G,C,C,G,...,T,G,C,C,C,C,C,G,C,EI
2,G,A,G,G,T,G,A,A,G,G,...,A,C,G,G,G,G,A,T,G,EI
3,G,G,G,C,T,G,C,G,T,T,...,G,T,T,T,T,C,C,C,C,EI
4,G,C,T,C,A,G,C,C,C,C,...,C,T,T,G,A,C,C,C,T,EI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3185,T,C,T,C,T,T,C,C,C,T,...,T,C,C,T,C,T,C,T,T,N
3186,G,A,G,C,T,C,C,C,A,G,...,G,C,A,C,A,G,C,T,G,N
3187,T,C,T,C,G,G,G,G,G,C,...,G,T,G,T,G,T,G,T,C,N
3188,A,T,T,C,T,A,C,T,T,A,...,C,C,A,A,A,A,C,A,A,N
3189,A,G,G,C,T,G,C,C,T,A,...,A,G,T,A,C,C,A,T,T,N

### Pre-processing

In [10]:
# Checking the missing values
if DecisionTable.isna().any().any():
    print("Dataset has missing values")
    DecisionTable.fillna(DecisionTable.mode().iloc[0], inplace=True) # fill with columnwise most common
else:
    print("No missing values")

No missing values

In [11]:
# Checking dublicates
if DecisionTable.iloc[:, :-1].duplicated().any():
    print("Yes there are dublicates")
    # merge dublicates and last values is the most common one
    DecisionTable = DecisionTable.groupby(list(DecisionTable.columns[:-1]))['class'].agg(lambda x: x.mode()[0]).reset_index()
else:
    print("No dublicate")

Yes there are dublicates

### Creating Decision Rule System

In [12]:
DecisionRule = DecisionRuleCreatorFromDecisionTable(DecisionTable)
DecisionRule

  0%|                                                                                                                                              | 0/3005 [00:00<?, ?it/s]/Users/durdymk/Desktop/DrDt/drdt/helper_functions.py:199: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r[mask_row] = np.nan
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 3005/3005 [03:23<00:00, 14.74it/s]

,Base1,Base2,Base3,Base4,Base5,Base6,Base7,Base8,Base9,Base10,...,Base52,Base53,Base54,Base55,Base56,Base57,Base58,Base59,Base60,class
0,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IE
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3000,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
3001,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
3002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,N
3003,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N
3004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IE

In [13]:
DecisionRule.to_csv('/Users/durdymk/Desktop/DrDt/datasets/DecisionRuleSystems/DRS_molecular_biology', index=False)

# Chess (King-Rook vs. King-Pawn)

In [14]:
chess_king_rook_vs_king_pawn = fetch_ucirepo(id=22) 
  
X = chess_king_rook_vs_king_pawn.data.features 
y = chess_king_rook_vs_king_pawn.data.targets 

#rename target name 'poisonous' to 'class'
y = y.rename(columns={'wtoeg': 'class'})

In [15]:
DecisionTable = pd.concat([X, y], axis=1)
DecisionTable

,bkblk,bknwy,bkon8,bkona,bkspr,bkxbq,bkxcr,bkxwp,blxwp,bxqsq,...,skrxp,spcop,stlmt,thrsk,wkcti,wkna8,wknck,wkovl,wkpos,class
f,f,f,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,t,t,n,won
f,f,f,f,t,f,f,f,f,f,f,...,f,f,f,f,f,f,t,t,n,won
f,f,f,f,t,f,t,f,f,f,f,...,f,f,f,f,f,f,t,t,n,won
f,f,f,f,f,f,f,f,t,f,f,...,f,f,f,f,f,f,t,t,n,won
f,f,f,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,t,t,n,won
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
t,f,f,f,f,f,t,f,f,f,f,...,f,t,f,f,t,f,t,f,n,nowin
t,f,f,f,f,f,t,f,f,f,f,...,f,t,f,f,t,f,t,f,n,nowin
t,f,f,f,f,f,t,f,f,f,f,...,f,t,f,f,t,f,t,f,n,nowin
t,f,t,f,f,f,t,f,f,f,f,...,f,t,f,f,t,f,f,f,n,nowin
t,f,t,f,f,f,t,f,f,f,f,...,f,t,f,f,t,f,f,f,n,nowin

### Pre-processing

In [16]:
# Checking the missing values
if DecisionTable.isna().any().any():
    print("Dataset has missing values")
    DecisionTable.fillna(DecisionTable.mode().iloc[0], inplace=True) # fill with columnwise most common
else:
    print("No missing values")

No missing values

In [17]:
# Checking dublicates
if DecisionTable.iloc[:, :-1].duplicated().any():
    print("Yes there are dublicates")
    # merge dublicates and last values is the most common one
    DecisionTable = DecisionTable.groupby(list(DecisionTable.columns[:-1]))['class'].agg(lambda x: x.mode()[0]).reset_index()
else:
    print("No dublicate")

Yes there are dublicates

### Creating Decision Rule System

In [18]:
DecisionRule = DecisionRuleCreatorFromDecisionTable(DecisionTable)
DecisionRule

  0%|                                                                                                                                              | 0/3133 [00:00<?, ?it/s]/Users/durdymk/Desktop/DrDt/drdt/helper_functions.py:199: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r[mask_row] = np.nan
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 3133/3133 [01:12<00:00, 43.07it/s]

,bkblk,bknwy,bkon8,bkona,bkspr,bkxbq,bkxcr,bkxwp,blxwp,bxqsq,...,skrxp,spcop,stlmt,thrsk,wkcti,wkna8,wknck,wkovl,wkpos,class
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,t,NaN,NaN,NaN,NaN,nowin
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,t,NaN,NaN,NaN,NaN,nowin
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,t,NaN,NaN,NaN,NaN,nowin
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,t,NaN,NaN,NaN,NaN,nowin
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,won
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nowin
3129,t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,won
3130,t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,won
3131,t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,won
3132,t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,won

In [19]:
DecisionRule.to_csv('/Users/durdymk/Desktop/DrDt/datasets/DecisionRuleSystems/DRS_chess', index=False)

# Soybean

In [20]:
soybean_large = fetch_ucirepo(id=90) 

X = soybean_large.data.features 
y = soybean_large.data.targets

In [21]:
DecisionTable = pd.concat([X, y], axis=1)
DecisionTable

,date,plant-stand,precip,temp,hail,crop-hist,area-damaged,severity,seed-tmt,germination,...,sclerotia,fruit-pods,fruit-spots,seed,mold-growth,seed-discolor,seed-size,shriveling,roots,class
0,6.0,0.0,2.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,diaporthe-stem-canker
1,4.0,0.0,2.0,1.0,0.0,2.0,0.0,2.0,1.0,1.0,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,diaporthe-stem-canker
2,3.0,0.0,2.0,1.0,0.0,1.0,0.0,2.0,1.0,2.0,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,diaporthe-stem-canker
3,3.0,0.0,2.0,1.0,0.0,1.0,0.0,2.0,0.0,1.0,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,diaporthe-stem-canker
4,6.0,0.0,2.0,1.0,0.0,2.0,0.0,1.0,0.0,2.0,...,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,diaporthe-stem-canker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2-4-d-injury
303,1.0,1.0,NaN,0.0,NaN,1.0,0.0,NaN,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,herbicide-injury
304,0.0,1.0,NaN,0.0,NaN,0.0,3.0,NaN,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,herbicide-injury
305,1.0,1.0,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,herbicide-injury
306,1.0,1.0,NaN,0.0,NaN,1.0,3.0,NaN,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,herbicide-injury

### Pre-processing

In [22]:
# Checking the missing values
if DecisionTable.isna().any().any():
    print("Dataset has missing values")
    DecisionTable.fillna(DecisionTable.mode().iloc[0], inplace=True) # fill with columnwise most common
else:
    print("No missing values")

Dataset has missing values

In [23]:
# Checking dublicates
if DecisionTable.iloc[:, :-1].duplicated().any():
    print("Yes there are dublicates")
    # merge dublicates and last values is the most common one
    DecisionTable = DecisionTable.groupby(list(DecisionTable.columns[:-1]))['class'].agg(lambda x: x.mode()[0]).reset_index()
else:
    print("No dublicate")

Yes there are dublicates

### Creating Decision Rule System

In [24]:
DecisionRule = DecisionRuleCreatorFromDecisionTable(DecisionTable)
DecisionRule

  0%|                                                                                                                                               | 0/303 [00:00<?, ?it/s]/Users/durdymk/Desktop/DrDt/drdt/helper_functions.py:199: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  r[mask_row] = np.nan
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 303/303 [00:04<00:00, 74.12it/s]

,date,plant-stand,precip,temp,hail,crop-hist,area-damaged,severity,seed-tmt,germination,...,external-decay,mycelium,int-discolor,fruit-pods,fruit-spots,seed-discolor,seed-size,shriveling,roots,class
0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,anthracnose
1,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,phytophthora-rot
2,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,phytophthora-rot
3,0.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,brown-spot
4,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rhizoctonia-root-rot
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,frog-eye-leaf-spot
299,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,frog-eye-leaf-spot
300,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,frog-eye-leaf-spot
301,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,anthracnose
302,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,anthracnose

In [25]:
DecisionRule.to_csv('/Users/durdymk/Desktop/DrDt/datasets/DecisionRuleSystems/DRS_soybean', index=False)

# Tic Tac Toe

In [ ]:
with resources.path('datasets.UCIMLDatasets', "tic-tac-toe.csv") as dataset_path:
    DecisionTable = pd.read_csv(dataset_path, header=None)

DecisionTable.columns = ["top-left-square", "top-middle-square", "top-right-square", "middle-left-square", "middle-middle-square", "middle-right-square", "bottom-left-square", "bottom-middle-square", "bottom-right-square", "class"]

DecisionTable

### Pre-processing

In [ ]:
# Checking the missing values
if DecisionTable.isna().any().any():
    print("Dataset has missing values")
    DecisionTable.fillna(DecisionTable.mode().iloc[0], inplace=True) # fill with columnwise most common
else:
    print("No missing values")

In [ ]:
# Checking dublicates
if DecisionTable.iloc[:, :-1].duplicated().any():
    print("Yes there are dublicates")
    # merge dublicates and last values is the most common one
    DecisionTable = DecisionTable.groupby(list(DecisionTable.columns[:-1]))['class'].agg(lambda x: x.mode()[0]).reset_index()
else:
    print("No dublicate")

### Creating Decision Rule System

In [ ]:
DecisionRule = DecisionRuleCreatorFromDecisionTable(DecisionTable)

DecisionRule

In [ ]:
DecisionRule.to_csv('/Users/durdymk/Desktop/DrDt/datasets/DecisionRuleSystems/DRS_tic-tac-toe', index=False)

# Car Evaluation

In [ ]:
with resources.path('datasets.UCIMLDatasets', "car_evaluation.csv") as dataset_path:
    DecisionTable = pd.read_csv(dataset_path, header=None)

DecisionTable.columns = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "class"] 

DecisionTable

### Pre-processing

In [ ]:
# Checking the missing values
if DecisionTable.isna().any().any():
    print("Dataset has missing values")
    DecisionTable.fillna(DecisionTable.mode().iloc[0], inplace=True) # fill with columnwise most common
else:
    print("No missing values")

In [ ]:
# Checking dublicates
if DecisionTable.iloc[:, :-1].duplicated().any():
    print("Yes there are dublicates")
    # merge dublicates and last values is the most common one
    DecisionTable = DecisionTable.groupby(list(DecisionTable.columns[:-1]))['class'].agg(lambda x: x.mode()[0]).reset_index()
else:
    print("No dublicate")

### Creating Decision Rule System

In [ ]:
DecisionRule = DecisionRuleCreatorFromDecisionTable(DecisionTable)
DecisionRule

In [ ]:
DecisionRule.to_csv('/Users/durdymk/Desktop/DrDt/datasets/DecisionRuleSystems/DRS_car_evaluation', index=False)

# Mushroom Dataset

In [ ]:
mushroom = fetch_ucirepo(id=73) 
  
X = mushroom.data.features 
y = mushroom.data.targets 

#rename target name 'poisonous' to 'class'
y = y.rename(columns={'poisonous': 'class'})

In [ ]:
DecisionTable = pd.concat([X, y], axis=1)
DecisionTable

### Pre-processing

In [ ]:
# Checking the missing values
if DecisionTable.isna().any().any():
    print("Dataset has missing values")
    DecisionTable.fillna(DecisionTable.mode().iloc[0], inplace=True) # fill with columnwise most common
else:
    print("No missing values")

In [ ]:
# Checking dublicates
if DecisionTable.iloc[:, :-1].duplicated().any():
    print("Yes there are dublicates")
    # merge dublicates and last values is the most common one
    DecisionTable = DecisionTable.groupby(list(DecisionTable.columns[:-1]))['class'].agg(lambda x: x.mode()[0]).reset_index()
else:
    print("No dublicate")

### Creating Decision Rule System

In [ ]:
DecisionRule = DecisionRuleCreatorFromDecisionTable(DecisionTable)
DecisionRule

In [ ]:
DecisionRule.to_csv('/Users/durdymk/Desktop/DrDt/datasets/DecisionRuleSystems/DRS_mushroom', index=False)

# Congressional Voting Records

In [ ]:
congressional_voting_records = fetch_ucirepo(id=105) 

X = congressional_voting_records.data.features 
y = congressional_voting_records.data.targets 

#rename target name 'Class' to 'class'
y = y.rename(columns={'Class': 'class'})

In [ ]:
DecisionTable = pd.concat([X, y], axis=1)
DecisionTable

### Pre-processing

In [ ]:
# Checking the missing values
if DecisionTable.isna().any().any():
    print("Dataset has missing values")
    DecisionTable.fillna(DecisionTable.mode().iloc[0], inplace=True) # fill with columnwise most common
else:
    print("No missing values")

In [ ]:
# Checking dublicates
if DecisionTable.iloc[:, :-1].duplicated().any():
    print("Yes there are dublicates")
    # merge dublicates and last values is the most common one
    DecisionTable = DecisionTable.groupby(list(DecisionTable.columns[:-1]))['class'].agg(lambda x: x.mode()[0]).reset_index()
else:
    print("No dublicate")

### Creating Decision Rule System

In [ ]:
DecisionRule = DecisionRuleCreatorFromDecisionTable(DecisionTable)
DecisionRule

In [ ]:
DecisionRule.to_csv('/Users/durdymk/Desktop/DrDt/datasets/DecisionRuleSystems/DRS_congressional_voting_records', index=False)

# Breast Cancer

In [ ]:
breast_cancer = fetch_ucirepo(id=14) 

X = breast_cancer.data.features 
y = breast_cancer.data.targets 

#rename target name 'Class' to 'class'
y = y.rename(columns={'Class': 'class'})

In [ ]:
DecisionTable = pd.concat([X, y], axis=1)
DecisionTable

### Pre-processing

In [ ]:
# Checking the missing values
if DecisionTable.isna().any().any():
    print("Dataset has missing values")
    DecisionTable.fillna(DecisionTable.mode().iloc[0], inplace=True) # fill with columnwise most common
else:
    print("No missing values")

In [ ]:
# Checking dublicates
if DecisionTable.iloc[:, :-1].duplicated().any():
    print("Yes there are dublicates")
    # merge dublicates and last values is the most common one
    DecisionTable = DecisionTable.groupby(list(DecisionTable.columns[:-1]))['class'].agg(lambda x: x.mode()[0]).reset_index()
else:
    print("No dublicate")

### Creating Decision Rule System

In [ ]:
DecisionRule = DecisionRuleCreatorFromDecisionTable(DecisionTable)
DecisionRule

In [ ]:
DecisionRule.to_csv('/Users/durdymk/Desktop/DrDt/datasets/DecisionRuleSystems/DRS_breast_cancer', index=False)

# Balance Scale

In [ ]:
balance_scale = fetch_ucirepo(id=12) 
  
# data (as pandas dataframes) 
X = balance_scale.data.features 
y = balance_scale.data.targets

In [ ]:
DecisionTable = pd.concat([X, y], axis=1)
DecisionTable

### Pre-processing

In [ ]:
# Checking the missing values
if DecisionTable.isna().any().any():
    print("Dataset has missing values")
    DecisionTable.fillna(DecisionTable.mode().iloc[0], inplace=True) # fill with columnwise most common
else:
    print("No missing values")

In [ ]:
# Checking dublicates
if DecisionTable.iloc[:, :-1].duplicated().any():
    print("Yes there are dublicates")
    # merge dublicates and last values is the most common one
    DecisionTable = DecisionTable.groupby(list(DecisionTable.columns[:-1]))['class'].agg(lambda x: x.mode()[0]).reset_index()
else:
    print("No dublicate")

### Creating Decision Rule System

In [ ]:
DecisionRule = DecisionRuleCreatorFromDecisionTable(DecisionTable)
DecisionRule

In [ ]:
DecisionRule.to_csv('/Users/durdymk/Desktop/DrDt/datasets/DecisionRuleSystems/DRS_balance_scale', index=False)

# Example

In [ ]:
example_DTable = pd.DataFrame(
[[1,1,1,1],
[0,1,0,2],
[1,1,0,2],
[0,0,1,3],
[1,0,0,3]],
columns=['f1','f2','f3','class']
)
example_DTable

In [ ]:
example_DRules = DecisionRuleCreatorFromDecisionTable(example_DTable)
example_DRules

In [ ]:
# example_DRules.to_csv('./Datasets/example_DRules.csv', index=False)