In [1]:
from importlib import resources
import pandas as pd

from drdt.algorithms import DynamicProgrammingAlgorithms

In [2]:
with resources.path('datasets.DecisionRuleSystems', 'DRS_car_evaluation') as dataset_path:
    S = pd.read_csv(dataset_path)   
S

     buying maint  doors persons lug_boot safety  class
0       NaN   NaN    NaN       2      NaN    NaN  unacc
1       NaN   NaN    NaN       2      NaN    NaN  unacc
2       NaN   NaN    NaN       2      NaN    NaN  unacc
3       NaN   NaN    NaN       2      NaN    NaN  unacc
4       NaN   NaN    NaN       2      NaN    NaN  unacc
...     ...   ...    ...     ...      ...    ...    ...
1723    low   NaN  5more     NaN      NaN    med   good
1724    low   NaN    NaN     NaN      NaN   high  vgood
1725    NaN   NaN    NaN     NaN      NaN    low  unacc
1726    low   NaN  5more     NaN      NaN    med   good
1727    low   NaN    NaN     NaN      big    NaN  vgood

[1728 rows x 7 columns]

In [3]:
alg = DynamicProgrammingAlgorithms(C="ESR")

In [4]:
depth = alg.A_DP(S)
depth

6